pipeline {
    agent any

    environment {
        IMAGE_NAME = "hugo-blog-prod"
        CONTAINER_NAME = "hugo-site-prod"
        PORT = "8000"
    }

    stages {
        stage('Nettoyage') {
            steps {
                echo "Nettoyage"
                sh "docker rm -f ${CONTAINER_NAME} || true"
            }
        }

        stage('Build Image') {
            steps {
                echo "Build de l'image Docker"
                sh "docker build -t ./.deployment/${IMAGE_NAME} ."
            }
        }

        stage('Deploy') {
            steps {
                echo "Déploiement du site"
                sh "docker run -d --name ./.deployment/${CONTAINER_NAME} -p ${PORT}:80 ${IMAGE_NAME}"
                echo "Site déployé sur http://localhost:${PORT}"
            }
        }
    }
}